# Generated by Django 5.1.15 on 2026-04-01 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                help_text="Что нужно сделать (например: 'Сделать дыхательную гимнастику', 'Выпить стакан воды')",
                max_length=300,
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                help_text="Сколько времени займет выполнение (не более 120 секунд (2 минуты))",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Время на выполнение (сек)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если это приятная привычка, которая будет вознаграждением за выполнение полезной привычки",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                help_text="Где вы будете выполнять привычку (например: 'Дом', 'Офис', 'Спортзал'",
                max_length=200,
                verbose_name="Место",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Чем себя вознаградить (например: 'Съесть вкусный йогурт', 'Послушать любимую музыку', 'Посмотреть сериал')",
                max_length=300,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="Во сколько выполнять привычку (например: 07:00, 15:30, 21:00",
                verbose_name="Время",
            ),
        ),
    ]
